Vamos a usar un w2v preentrenado en google news, y con tamaño 300

In [ ]:
import numpy as np
import gensim.downloader as api
w2v = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


Podemos ver el embed de

In [ ]:
w2v.get_vector('happy')[:10]

array([-0.0005188 ,  0.16015625,  0.0016098 ,  0.02539062,  0.09912109,
       -0.0859375 ,  0.32421875, -0.02172852,  0.13476562,  0.11035156],
      dtype=float32)

In [ ]:
w2v.get_vector('kenough')

KeyError: ignored

In [ ]:
def get_vect(word):
    try:
        return w2v.get_vector(word)
    except KeyError:
        return np.zeros(300)

In [ ]:
get_vect("kenough")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
get_vect('Happy')[:10]

array([ 0.05078125, -0.109375  , -0.12597656,  0.12402344,  0.12695312,
       -0.1484375 , -0.14941406,  0.16601562,  0.05151367, -0.11425781],
      dtype=float32)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(w2v.get_vector('happy').reshape(1, -1) , w2v.get_vector('Happy').reshape(1, -1))

array([[0.47028434]], dtype=float32)

In [ ]:
cosine_similarity(w2v.get_vector('happy').reshape(1, -1) , w2v.get_vector('happy').reshape(1, -1))

array([[1.0000002]], dtype=float32)

In [ ]:
cosine_similarity(w2v.get_vector('happy').reshape(1, -1) , w2v.get_vector('funny').reshape(1, -1))

array([[0.3270088]], dtype=float32)

In [ ]:
cosine_similarity(w2v.get_vector('happy').reshape(1, -1) , w2v.get_vector('sad').reshape(1, -1))

array([[0.53546154]], dtype=float32)

In [ ]:
w2v.similarity('happy', 'happy')

1.0

In [ ]:
w2v.similarity('happy', 'Happy')

0.47028428

In [ ]:
w2v.similarity('happy', 'funny')

0.32700878

In [ ]:
w2v.similarity('happy', 'kenough')

KeyError: ignored

In [ ]:
w2v.similarity('HAPPY', 'Happy')

0.40372944

In [ ]:
w2v.most_similar("happy")

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [ ]:
w2v.most_similar("HAPPY")

[('ENJOYING_THE', 0.7024169564247131),
 ('BYE_BYE', 0.6989719867706299),
 ('WAITING_FOR', 0.6888777017593384),
 ('DELIGHT', 0.6858440637588501),
 ('VICTORY_FOR', 0.6837770938873291),
 ('JOYOUS', 0.6824684143066406),
 ("'S_DAY", 0.6774148941040039),
 ('CATCHING', 0.6768207550048828),
 ("HARRY_'S", 0.6752324104309082),
 ('OLDEST', 0.673992395401001)]

In [ ]:
w2v.most_similar("GLAD")

[('attorney_Michele_Granda', 0.6228544116020203),
 ('Lee_Swislow', 0.5581809878349304),
 ('&_Lesbian_Advocates', 0.550981879234314),
 ('Bonauto', 0.5454815626144409),
 ('Gary_Buseck', 0.5425578355789185),
 ('Lesbian_Advocates', 0.5264952778816223),
 ('Defenders_GLAD', 0.5170184969902039),
 ('MassEquality', 0.5068147778511047),
 ('Gary_Buseck_legal', 0.5026320219039917),
 ('DOMA', 0.5012069940567017)]