In [ ]:
!pip3 install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 55.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 41.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 93.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 94.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 35.2 MB/s eta 0:00:00


In [ ]:
import numpy as np

In [ ]:
from transformers import AutoTokenizer,AutoModel,pipeline

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModel.from_pretrained("gpt2")

tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model.resize_token_embeddings(len(tokenizer))

pipe = pipeline('feature-extraction', model=model, tokenizer=tokenizer)

In [ ]:
tokenizer("Hola")

{'input_ids': [39, 5708], 'attention_mask': [1, 1]}

In [ ]:
tokenizer("hola")

{'input_ids': [3937, 64], 'attention_mask': [1, 1]}

In [ ]:
tokenizer("hello")

{'input_ids': [31373], 'attention_mask': [1]}

In [ ]:
tokenizer("my car")

{'input_ids': [1820, 1097], 'attention_mask': [1, 1]}

In [ ]:
tokenizer("my")

{'input_ids': [1820], 'attention_mask': [1]}

In [ ]:
tokenizer("car")

{'input_ids': [7718], 'attention_mask': [1]}

In [ ]:
tokenizer(" car")

{'input_ids': [1097], 'attention_mask': [1]}

In [ ]:
np.array(pipe("hello")).shape

(1, 1, 768)

In [ ]:
emb_1 = np.array(pipe("hello"))[0][0]
emb_2 = np.array(pipe("apple"))[0][0]
emb_3 = np.array(pipe("banana"))[0][0]
emb_4 = np.array(pipe(" banana"))[0][0]
emb_5 = np.array(pipe("car"))[0][0]

In [ ]:
emb_3[:30]

array([-0.19383569, -0.01230379, -0.37903357, -0.08307248, -0.07156385,
       -0.21990997,  0.53399104,  0.11801282, -0.1887823 ,  0.029421  ,
        0.35254335, -0.07336788, -0.03272052,  0.02920395, -0.11745388,
       -0.08498669, -0.03082361, -0.19734129,  0.06080289, -0.34656328,
        0.1353749 , -0.103932  , -0.22295983, -0.16035514, -0.07805098,
        0.15667059, -0.29117563, -0.18384968, -0.08102708, -0.30356044])

In [ ]:
emb_4[:30]

array([-0.15951642,  0.08847554, -0.50325608, -0.19344079, -0.08532201,
       -0.10277977, -0.49532557, -0.17655902, -0.29543617,  0.02834751,
        0.3717185 , -0.11272895, -0.17549248, -0.01447447, -0.15099677,
       -0.07685317, -0.1313657 , -0.2182246 ,  0.20424104, -0.22029842,
        0.13522935, -0.06283043, -0.20738252, -0.15325913, -0.03808989,
        0.05615237, -0.15543431, -0.15345533, -0.12934077, -0.39214709])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(emb_3.reshape(1, -1),emb_4.reshape(1, -1))

array([[0.99038435]])

In [ ]:
cosine_similarity(emb_3.reshape(1, -1),emb_5.reshape(1, -1))

array([[0.99758772]])

In [ ]:
cosine_similarity(emb_4.reshape(1, -1),emb_5.reshape(1, -1))

array([[0.98693486]])