# Preprocess (no es tan relevante, mirenlo despues)

In [ ]:
!wget https://github.com/Pietracoops/yugioh_cardlist_scraper/releases/download/V1.0.3/yugioh_database_csv.zip

--2024-10-24 22:19:18--  https://github.com/Pietracoops/yugioh_cardlist_scraper/releases/download/V1.0.3/yugioh_database_csv.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/562716749/8dd80598-afb8-41ff-8d79-0d6b7da17da1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241024%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241024T221918Z&X-Amz-Expires=300&X-Amz-Signature=ed52be26cd8e3ba9fba51b28ae72398f3fac4376aaaf14941dc3ab6767871d46&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dyugioh_database_csv.zip&response-content-type=application%2Foctet-stream [following]
--2024-10-24 22:19:18--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/562716749/8dd80598-afb8-41ff-8d79-0d6b7da17da1?X-Amz-Alg

In [ ]:
!unzip /content/yugioh_database_csv.zip

Archive:  /content/yugioh_database_csv.zip
  inflating: 2-PLAYER STARTER DECK YUYA & DECLAN (UK).csv  
  inflating: 2014 MEGA-TINS MEGA PACK.csv  
  inflating: 2014 MEGA-TINS.csv      
  inflating: 2015 MEGA-TINS MEGA PACK.csv  
  inflating: 2015 MEGA-TINS.csv      
  inflating: 2016 MEGA-TINS MEGA PACK.csv  
  inflating: 2016 MEGA-TINS.csv      
  inflating: 2017 MEGA-TINS MEGA PACK.csv  
  inflating: 2017 MEGA-TINS.csv      
  inflating: 2018 MEGA-TINS MEGA PACK.csv  
  inflating: 2018 MEGA-TINS.csv      
  inflating: 2019 GOLD SARCOPHAGUS TIN MEGA PACK.csv  
  inflating: 2019 GOLD SARCOPHAGUS TIN.csv  
  inflating: 2020 TIN OF LOST MEMORIES.csv  
  inflating: 2021 TIN OF ANCIENT BATTLES.csv  
  inflating: 2022 TIN OF THE PHARAOH'S GODS.csv  
  inflating: 5D's STARTER DECK 2008.csv  
  inflating: 5D's STARTER DECK 2009.csv  
  inflating: 5D's STARTER DECK DUELIST TOOLBOX.csv  
  inflating: ABSOLUTE POWERFORCE Sneak Peek.csv  
  inflating: ABSOLUTE POWERFORCE SPECIAL EDITION.csv  
  i

In [ ]:
import os
import pandas as pd

In [ ]:
data = []

for x in os.listdir():
    if not x.endswith(".csv"):
        continue
    print(x)
    df = pd.read_csv(x,sep="$")
    data.append(df)

PENDULUM DOMINATION STRUCTURE DECK.csv
STARDUST OVERDRIVE SPECIAL EDITION.csv
SHONEN JUMP membership Promotional Card - October 2014 -.csv
DUEL TERMINAL 4.csv
LEGENDARY COLLECTION.csv
COLLECTIBLE TIN SERIES 3 WAVE 1.csv
SPEED DUEL- TRIALS OF THE KINGDOM Sneak Peak.csv
SHONEN JUMP Promotional Card - November 2010 -.csv
IGNITION ASSAULT.csv
DUELIST PACK - YUSEI -.csv
TACTICAL EVOLUTION Sneak Peek.csv
HIDDEN ARSENAL 7 KNIGHT OF STARS.csv
RISING RAMPAGE Sneak Peek.csv
SHONEN JUMP ALPHA membership Promotional Card - September 2012 -.csv
SOUL FUSION Sneak Peek.csv
MAXIMUM CRISIS.csv
HIDDEN ARSENAL 2.csv
Yu-Gi-Oh! WORLD CHAMPIONSHIP 2011 Qualifier.csv
ORDER OF CHAOS Sneak Peek.csv
Yu-Gi-Oh! WORLD CHAMPIONSHIP 2013.csv
FUSION ENFORCERS.csv
Structure Decks.csv
SHONEN JUMP membership Promotional Card - August 2018 -.csv
SHONEN JUMP Championship 2005.csv
CRIMSON CRISIS.csv
Speed Duel- Battle City Box.csv
GENERATION FORCE Sneak Peek.csv
METAL RAIDERS.csv
SHONEN JUMP Promotional Card - November 200

In [ ]:
dataset = pd.concat(data)

In [ ]:
dataset

Passcode                                               Name     Status  \
0   83303851.0                        D/D/D Chaos King Apocalypse  Unlimited   
1   19302550.0                                  D/D Savant Newton  Unlimited   
2   46796664.0                              D/D Savant Copernicus  Unlimited   
3   72181263.0                                        D/D Orthros  Unlimited   
4   19580308.0                                          D/D Lamia  Unlimited   
..         ...                                                ...        ...   
96  36730805.0                                          Speedlift  Unlimited   
97  36111775.0                                      Pendulum Halt  Unlimited   
98  63509474.0                                  Whitefish Salvage  Unlimited   
99  84731222.0                                   Memories of Hope  Unlimited   
0   77498348.0  Black Luster Soldier - Envoy of the Evening Tw...  Unlimited   

   Attribute                           type  link link_arrows  rank  \
0       DARK        [Fiend/Pendulum/Effect]   NaN         NaN   NaN   
1       DARK        [Fiend/Pendulum/Effect]   NaN         NaN   NaN   
2       DARK        [Fiend/Pendulum/Effect]   NaN         NaN   NaN   
3       DARK  [Fiend/Pendulum/Tuner/Effect]   NaN         NaN   NaN   
4       DARK           [Fiend/Tuner/Effect]   NaN         NaN   NaN   
..       ...                            ...   ...         ...   ...   
96     SPELL                            NaN   NaN         NaN   NaN   
97     SPELL                            NaN   NaN         NaN   NaN   
98     SPELL                            NaN   NaN         NaN   NaN   
99     SPELL                            NaN   NaN         NaN   NaN   
0       DARK               [Warrior/Effect]   NaN         NaN   NaN   

    pendulum_scale  level  ... defense spell_attribute summoning_condition  \
0              4.0    7.0  ...  2000.0             NaN                 NaN   
1             10.0    7.0  ...     0.0             NaN                 NaN   
2              1.0    4.0  ...     0.0             NaN                 NaN   
3              3.0    4.0  ...  1800.0             NaN                 NaN   
4              NaN    1.0  ...  1900.0             NaN                 NaN   
..             ...    ...  ...     ...             ...                 ...   
96             NaN    NaN  ...     NaN      Quick-Play                 NaN   
97             NaN    NaN  ...     NaN             NaN                 NaN   
98             NaN    NaN  ...     NaN      Continuous                 NaN   
99             NaN    NaN  ...     NaN             NaN                 NaN   
0              NaN    8.0  ...    2500             NaN                 NaN   

                                   pendulum_condition  \
0   You can banish 2 "D/D" monsters from your Grav...   
1   You cannot Pendulum Summon monsters, except "D...   
2   You cannot Pendulum Summon monsters, except "D...   
3   Once per turn: You can target 1 Spell/Trap Car...   
4                                                 NaN   
..                                                ...   
96                                                NaN   
97                                                NaN   
98                                                NaN   
99                                                NaN   
0                                                 NaN   

                                            card_text  \
0   During your opponent's turn, if this card is i...   
1   You can discard this card, then target 1 "D/D"...   
2   If this card is Normal or Special Summoned: Yo...   
3   When you take battle or effect damage: You can...   
4   If this card is in your hand or GY: You can se...   
..                                                ...   
96  If you control exactly 1 Tuner and no other mo...   
97  If you have 3 or more face-up Pendulum Monster...   
98  You can target 1 Fish monster in your GY; add ...   


In [ ]:
!head "EXTREME VICTORY Sneak Peek.csv"

Passcode$Name$Status$Attribute$type$link$link_arrows$rank$pendulum_scale$level$attack$defense$spell_attribute$summoning_condition$pendulum_condition$card_text$card_supports$card_anti_supports$card_actions$effect_types$
10028593$Reborn Tengu$Unlimited$WIND$[Beast-Warrior/Effect]$$$$$4$1700$600$$$$If this face-up card leaves the field: Special Summon 1 "Reborn Tengu" from your Deck.$$$Activates when it leaves the field$Trigger$


In [ ]:
pd.read_csv("/content/2-PLAYER STARTER DECK YUYA & DECLAN (UK).csv",sep="$")

Passcode                         Name     Status Attribute  \
0   56619314  D/D/D Dragon King Pendragon  Unlimited      DARK   
1   11761845              Beast of Talwar  Unlimited      DARK   
2   49881766            Archfiend Soldier  Unlimited      DARK   
3   54343893                  Vice Dragon  Unlimited      DARK   
4   85306040    Goblin Elite Attack Force  Unlimited     EARTH   
5   84914462                Axe Dragonute  Unlimited      DARK   
6   94664694                Mad Archfiend  Unlimited      DARK   
7   12235475             Fabled Ashenveil  Unlimited     LIGHT   
8   51838385             Theban Nightmare  Unlimited     LIGHT   
9   16719802           Bright Star Dragon  Unlimited     LIGHT   
10  20586572              Exploder Dragon  Unlimited     EARTH   
11  48343627               Grave Squirmer  Unlimited      DARK   
12  97169186              Smashing Ground  Unlimited     SPELL   
13   5318639       Mystical Space Typhoon  Unlimited     SPELL   
14  40619825               Axe of Despair  Unlimited     SPELL   
15  10012614            Banner of Courage  Unlimited     SPELL   
16  44095762                 Mirror Force  Unlimited      TRAP   
17  62279055               Magic Cylinder  Unlimited      TRAP   
18  60082869                 Dust Tornado  Unlimited      TRAP   
19  57882509             Mask of Weakness  Unlimited      TRAP   
20  97077563          Call of the Haunted  Unlimited      TRAP   
21  19221310        Odd-Eyes Saber Dragon  Unlimited     LIGHT   
22  43096270           Alexandrite Dragon  Unlimited     LIGHT   
23  15025844                 Mystical Elf  Unlimited     LIGHT   
24  53025096              Odd-Eyes Dragon  Unlimited      DARK   
25  70095154                 Cyber Dragon  Unlimited     LIGHT   
26  66337215           Herald of Creation  Unlimited     LIGHT   
27  15960641                Mirage Dragon  Unlimited     LIGHT   
28  93013676                   Maha Vailo  Unlimited     LIGHT   
29  38520918               Ancient Dragon  Unlimited     LIGHT   
30  14506878         DUCKER Mobile Cannon  Unlimited     LIGHT   
31  60694662                    Skelengel  Unlimited     LIGHT   
32  51196174               The Calculator  Unlimited     LIGHT   
33  53129443                    Dark Hole  Unlimited     SPELL   
34  70046172              Rush Recklessly  Unlimited     SPELL   
35  65169794                Black Pendant  Unlimited     SPELL   
36  99597615           Malevolent Nuzzler  Unlimited     SPELL   
37   4206964                    Trap Hole  Unlimited      TRAP   
38  44509898               Pinpoint Guard  Unlimited      TRAP   
39  14315573                Negate Attack  Unlimited      TRAP   

                     type  link  link_arrows  rank  pendulum_scale  level  \
0          [Fiend/Effect]   NaN          NaN   NaN             NaN    7.0   
1          [Fiend/Normal]   NaN          NaN   NaN             NaN    6.0   
2          [Fiend/Normal]   NaN          NaN   NaN             NaN    4.0   
3         [Dragon/Effect]   NaN          NaN   NaN             NaN    5.0   
4          [Fiend/Effect]   NaN          NaN   NaN             NaN    4.0   
5         [Dragon/Effect]   NaN          NaN   NaN             NaN    4.0   
6          [Fiend/Effect]   NaN          NaN   NaN             NaN    4.0   
7          [Fiend/Effect]   NaN          NaN   NaN             NaN    4.0   
8          [Fiend/Effect]   NaN          NaN   NaN             NaN    4.0   
9         [Dragon/Effect]   NaN          NaN   NaN             NaN    4.0   
10        [Dragon/Effect]   NaN          NaN   NaN             NaN    3.0   
11         [Fiend/Effect]   NaN          NaN   NaN             NaN    1.0   
12                    NaN   NaN          NaN   NaN             NaN    NaN   
13                    NaN   NaN          NaN   NaN             NaN    NaN   
14                    NaN   NaN          NaN   NaN             NaN    NaN   
15                    NaN   NaN          NaN   NaN             Na

In [ ]:
dataset = dataset.sort_values("Passcode")

In [ ]:
ds = dataset.dropna(subset=["Passcode"])
ds.Passcode = ds.Passcode.astype(int)
ds.set_index("Passcode",inplace=True)

<ipython-input-11-464b9c90fc49>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds.Passcode = ds.Passcode.astype(int)


In [ ]:
ds

Name     Status Attribute  \
Passcode                                                   
2511              Labrynth Cooclock  Unlimited      DARK   
10000           Ten Thousand Dragon  Unlimited      DARK   
27551                 Limit Reverse  Unlimited      TRAP   
27551                 Limit Reverse  Unlimited      TRAP   
27551                 Limit Reverse  Unlimited      TRAP   
...                             ...        ...       ...   
99991455  Raijin the Breakbolt Star  Unlimited     LIGHT   
99991455  Raijin the Breakbolt Star  Unlimited     LIGHT   
99995595        Recycling Batteries  Unlimited     SPELL   
99995595        Recycling Batteries  Unlimited     SPELL   
99995595        Recycling Batteries  Unlimited     SPELL   

                             type  link link_arrows  rank  pendulum_scale  \
Passcode                                                                    
2511               [Fiend/Effect]   NaN         NaN   NaN             NaN   
10000             [Dragon/Effect]   NaN         NaN   NaN             NaN   
27551                         NaN   NaN         NaN   NaN             NaN   
27551                         NaN   NaN         NaN   NaN             NaN   
27551                         NaN   NaN         NaN   NaN             NaN   
...                           ...   ...         ...   ...             ...   
99991455  [Warrior/Fusion/Effect]   NaN         NaN   NaN             NaN   
99991455  [Warrior/Fusion/Effect]   NaN         NaN   NaN             NaN   
99995595                      NaN   NaN         NaN   NaN             NaN   
99995595                      NaN   NaN         NaN   NaN             NaN   
99995595                      NaN   NaN         NaN   NaN             NaN   

          level attack defense spell_attribute  \
Passcode                                         
2511        1.0    0.0     0.0             NaN   
10000      10.0      ?       ?             NaN   
27551       NaN    NaN     NaN      Continuous   
27551       NaN    NaN     NaN      Continuous   
27551       NaN    NaN     NaN      Continuous   
...         ...    ...     ...             ...   
99991455   10.0   3000    2200             NaN   
99991455   10.0   3000    2200             NaN   
99995595    NaN    NaN     NaN             NaN   
99995595    NaN    NaN     NaN             NaN   
99995595    NaN    NaN     NaN             NaN   

                                        summoning_condition  \
Passcode                                                      
2511                                                    NaN   
10000                                                   NaN   
27551                                                   NaN   
27551                                                   NaN   
27551                                                   NaN   
...                                                     ...   
99991455  1 Level 5 or higher LIGHT Warrior monster + 1 ...   
99991455  1 Level 5 or higher LIGHT Warrior monster + 1 ...   
99995595                                                NaN   
99995595                                                NaN   
99995595                                                NaN   

         pendulum_condition  \
Passcode                      
2511                    NaN   
10000                   NaN   
27551                   NaN   
27551                   NaN   
27551                   NaN   
...                     ...   
99991455                NaN   
99991455                NaN   
99995595                NaN   
99995595                NaN   
99995595                NaN   

                                                  card_text  \
Passcode                                                      
2511      (Quick Effect): You can discard this card; thi...   
10000     Cannot be Normal Summoned/Set. Must be Special...   
27551     Target 1 monster with 1000 or less ATK in your...   
27551     Target 1 monster with 1000 or less ATK in your..

In [ ]:
ds.card_text

Passcode
2511        (Quick Effect): You can discard this card; thi...
10000       Cannot be Normal Summoned/Set. Must be Special...
27551       Target 1 monster with 1000 or less ATK in your...
27551       Target 1 monster with 1000 or less ATK in your...
27551       Target 1 monster with 1000 or less ATK in your...
                                  ...                        
99991455    If this card attacks a Defense Position monste...
99991455    If this card attacks a Defense Position monste...
99995595    Target 2 Thunder-Type monsters with 1500 or le...
99995595    Target 2 Thunder-Type monsters with 1500 or le...
99995595    Target 2 Thunder-Type monsters with 1500 or le...
Name: card_text, Length: 29539, dtype: object

In [ ]:
import re
regex = r"[^\w\d]+"

def clean_split(card_text):
    clean = re.sub(regex," ",card_text)
    return clean.lower().split()


ds["tokenized_text"] = ds.card_text.map(lambda x: clean_split(x))
ds.tokenized_text

<ipython-input-14-1b180f6e4211>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["tokenized_text"] = ds.card_text.map(lambda x: clean_split(x))


Passcode
2511        [quick, effect, you, can, discard, this, card,...
10000       [cannot, be, normal, summoned, set, must, be, ...
27551       [target, 1, monster, with, 1000, or, less, atk...
27551       [target, 1, monster, with, 1000, or, less, atk...
27551       [target, 1, monster, with, 1000, or, less, atk...
                                  ...                        
99991455    [if, this, card, attacks, a, defense, position...
99991455    [if, this, card, attacks, a, defense, position...
99995595    [target, 2, thunder, type, monsters, with, 150...
99995595    [target, 2, thunder, type, monsters, with, 150...
99995595    [target, 2, thunder, type, monsters, with, 150...
Name: tokenized_text, Length: 29539, dtype: object

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('universal_tagset')

ds["tags"] = ds.tokenized_text.map(lambda x: nltk.tag.pos_tag(x,tagset="universal")).map(lambda x: [y[1] for y in x])
ds["tags"]

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.
<ipython-input-15-d2b2187b1e5d>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ds["tags"] = ds.tokenized_text.map(lambda x: nltk.tag.pos_tag(x,tagset="universal")).map(lambda x: [y[1] for y in x])


Passcode
2511        [ADJ, NOUN, PRON, VERB, VERB, DET, NOUN, DET, ...
10000       [ADV, VERB, ADJ, VERB, VERB, VERB, VERB, ADJ, ...
27551       [NOUN, NUM, NOUN, ADP, NUM, CONJ, ADJ, NOUN, A...
27551       [NOUN, NUM, NOUN, ADP, NUM, CONJ, ADJ, NOUN, A...
27551       [NOUN, NUM, NOUN, ADP, NUM, CONJ, ADJ, NOUN, A...
                                  ...                        
99991455    [ADP, DET, NOUN, VERB, DET, NOUN, NOUN, NOUN, ...
99991455    [ADP, DET, NOUN, VERB, DET, NOUN, NOUN, NOUN, ...
99995595    [NOUN, NUM, NOUN, NOUN, NOUN, ADP, NUM, CONJ, ...
99995595    [NOUN, NUM, NOUN, NOUN, NOUN, ADP, NUM, CONJ, ...
99995595    [NOUN, NUM, NOUN, NOUN, NOUN, ADP, NUM, CONJ, ...
Name: tags, Length: 29539, dtype: object

In [ ]:
import numpy as np

In [ ]:
import functools

tokens = ds.tokenized_text.map(lambda x: set(x))
tokens = functools.reduce(lambda x,y : x.union(y),tokens)
tokens

{'glow',
 'harpies',
 'alphancall',
 'punisher',
 'handmaiden',
 'pegasus',
 'legacies',
 'pumpkin',
 'resolving',
 'his',
 'specific',
 'lumina',
 'mirror',
 'saber',
 'well',
 'shipping',
 'boundless',
 'trigger',
 'retribution',
 'sol',
 'vierte',
 'careful',
 'files',
 'born',
 'lives',
 'kataroost',
 'parade',
 'tributing',
 'increased',
 'stars',
 'pact',
 'resolution',
 'earthbound',
 '73',
 'poisonous',
 'illusionist',
 'megalith',
 '89',
 'count',
 'avian',
 'conquering',
 'recon',
 'psycho',
 'legendary',
 'guarding',
 'icicle',
 'obeys',
 '3000',
 'rasenryu',
 'resembles',
 'booting',
 'turbo',
 'disaster',
 'hunter',
 'impersonation',
 'enchanted',
 'harmattan',
 'suppression',
 'helios',
 'schedule',
 'turquoise',
 'chakanine',
 'diplos',
 'seeks',
 'lulu',
 'transmissions',
 'water',
 'deceptive',
 'headbatt',
 'notebook',
 'ahrima',
 'retroactive',
 'sweet',
 'charles',
 'adventure',
 'gallatin',
 'hated',
 'believe',
 'gigantes',
 'xiezhi',
 'generations',
 'light',
 'a

In [ ]:
len(tokens)

7255

In [ ]:
enumerated_tokens = list(enumerate(sorted(tokens)+["<FILL>"]))
enumerated_tokens

[(0, '0'),
 (1, '000'),
 (2, '000continue'),
 (3, '003'),
 (4, '004'),
 (5, '005'),
 (6, '006'),
 (7, '009'),
 (8, '05'),
 (9, '0x00'),
 (10, '0x1i'),
 (11, '1'),
 (12, '10'),
 (13, '100'),
 (14, '1000'),
 (15, '10000'),
 (16, '101'),
 (17, '102'),
 (18, '103'),
 (19, '104'),
 (20, '105'),
 (21, '107'),
 (22, '11'),
 (23, '1100'),
 (24, '12'),
 (25, '1200'),
 (26, '1250'),
 (27, '13'),
 (28, '1300'),
 (29, '1400'),
 (30, '1450'),
 (31, '15'),
 (32, '1500'),
 (33, '1600'),
 (34, '1700'),
 (35, '1800'),
 (36, '1850'),
 (37, '1900'),
 (38, '1950'),
 (39, '1st'),
 (40, '2'),
 (41, '20'),
 (42, '200'),
 (43, '2000'),
 (44, '2050'),
 (45, '2100'),
 (46, '2200'),
 (47, '2300'),
 (48, '2400'),
 (49, '2500'),
 (50, '26'),
 (51, '2600'),
 (52, '27'),
 (53, '2700'),
 (54, '2800'),
 (55, '29'),
 (56, '2nd'),
 (57, '3'),
 (58, '30'),
 (59, '300'),
 (60, '3000'),
 (61, '31'),
 (62, '32'),
 (63, '3300'),
 (64, '3500'),
 (65, '37'),
 (66, '39'),
 (67, '3rd'),
 (68, '4'),
 (69, '400'),
 (70, '4000'),
 

In [ ]:
tags = ds.tags.map(lambda x: set(x))
tags = functools.reduce(lambda x,y : x.union(y),tags)
tags

{'.',
 'ADJ',
 'ADP',
 'ADV',
 'CONJ',
 'DET',
 'NOUN',
 'NUM',
 'PRON',
 'PRT',
 'VERB',
 'X'}

In [ ]:
enumerated_tags = list(enumerate(sorted(tags)))
enumerated_tags

[(0, '.'),
 (1, 'ADJ'),
 (2, 'ADP'),
 (3, 'ADV'),
 (4, 'CONJ'),
 (5, 'DET'),
 (6, 'NOUN'),
 (7, 'NUM'),
 (8, 'PRON'),
 (9, 'PRT'),
 (10, 'VERB'),
 (11, 'X')]

In [ ]:
import torch
import numpy as np

token --> class


In [ ]:
model = lambda x: "AS"

In [ ]:
model("axe")

'AS'

[ ctx , ctx , ctx , word , ctx , ctx , ctx] --> class

In [ ]:
model(["can","equip","an","AXE", "to","this","monster"])

'AS'

[ ctx , ctx , ctx , word , ctx , ctx , ctx] --> [ cls_prob , cls_prob , cls_prob ]

In [ ]:
model = lambda x: [0.2,0.2,0.5,0.1]

In [ ]:
model(["can","equip","an","AXE", "to","this","monster"])

[0.2, 0.2, 0.5, 0.1]

![image](https://www.americanscientist.org/sites/americanscientist.org/files/20144141249210337-2014-05TechnologueFp170.jpg)

In [ ]:
word = np.array([ 1, 0 , 1])

In [ ]:
[1,0,1,[1,0,1]] --> [1,0,1,1,0,1]

In [ ]:
word

array([1, 0, 1])

In [ ]:
model = np.array([ [.2,.3,.8,.1] , [.5,.8,.7,.4] , [.5,.8,.7,.4] ])
model

array([[0.2, 0.3, 0.8, 0.1],
       [0.5, 0.8, 0.7, 0.4],
       [0.5, 0.8, 0.7, 0.4]])

In [ ]:
np.matmul(word,model)

array([0.7, 1.1, 1.5, 0.5])

In [ ]:
model = np.array([ [.2,-.3,.8,.0] , [.9,.9,.9,.9] , [.0,.5,-.3,.1] ])
model

array([[ 0.2, -0.3,  0.8,  0. ],
       [ 0.9,  0.9,  0.9,  0.9],
       [ 0. ,  0.5, -0.3,  0.1]])

In [ ]:
np.matmul(word,model)

array([0.2, 0.2, 0.5, 0.1])

In [ ]:
import torch

In [ ]:
np.matmul(np.matmul(word,model),torch.rand(4,4))

tensor([0.5928, 0.4875, 0.1570, 0.2587], dtype=torch.float64)

In [ ]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)

In [ ]:
device

'cpu'

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_a = nn.Linear(3,4)
        self.dense_b = nn.Linear(4,4)

    def forward(self, x):
        x = self.dense_a(x)
        x = self.dense_b(x)
        return x

In [ ]:
tagger = POS_Tagger().to(device)

In [ ]:
tagger(word)

TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [ ]:
tagger(torch.Tensor(word))

tensor([ 0.4254,  0.2415, -0.1904,  0.0856], grad_fn=<ViewBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_a = nn.Linear(3,4)
        self.dense_b = nn.Linear(4,4)

    def forward(self, x):
        x = self.dense_a(x)
        x = self.dense_b(x)
        print(x)
        return nn.functional.softmax(x,0)

In [ ]:
tagger = POS_Tagger().to(device)
tagger(torch.Tensor(word))

tensor([ 0.1518, -0.3486, -0.2711, -0.1150], grad_fn=<ViewBackward0>)


tensor([0.3303, 0.2003, 0.2164, 0.2530], grad_fn=<SoftmaxBackward0>)

In [ ]:
list(tagger.dense_a.parameters())

[Parameter containing:
 tensor([[ 0.3069, -0.3146, -0.5322],
         [ 0.3901, -0.3351,  0.5018],
         [-0.5493,  0.3876,  0.4555],
         [ 0.1835, -0.0340,  0.5205]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3029, -0.2337,  0.4987,  0.1769], requires_grad=True)]

In [ ]:
class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_a = nn.Linear(3,4,bias=False)
        self.dense_b = nn.Linear(4,4,bias=False)

    def forward(self, x):
        x = self.dense_a(x)
        x = self.dense_b(x)
        print(x)
        return nn.functional.softmax(x,0)

tagger = POS_Tagger().to(device)
list(tagger.dense_a.parameters())

[Parameter containing:
 tensor([[ 0.4515, -0.5228,  0.3608],
         [ 0.0107,  0.3302, -0.0735],
         [-0.0433, -0.3962,  0.1851],
         [-0.4702, -0.5203, -0.1675]], requires_grad=True)]

In [ ]:
tagger(torch.Tensor([-9,2,9]))

tensor([ 0.9348, -0.2321, -0.0889, -0.2795], grad_fn=<SqueezeBackward4>)


tensor([0.5083, 0.1582, 0.1826, 0.1509], grad_fn=<SoftmaxBackward0>)

In [ ]:
tagger(torch.Tensor([-900,2,9]))

tensor([302.3881,   3.0163, -47.8609, -31.9228], grad_fn=<SqueezeBackward4>)


tensor([1., 0., 0., 0.], grad_fn=<SoftmaxBackward0>)

In [ ]:
tagger(torch.Tensor([-900,0.5,9]))

tensor([301.9636,   3.1550, -47.5259, -31.9636], grad_fn=<SqueezeBackward4>)


tensor([1., 0., 0., 0.], grad_fn=<SoftmaxBackward0>)

In [ ]:
tagger(torch.Tensor([1,0.5,1]))

tensor([-0.4942, -0.0588,  0.0353,  0.0475], grad_fn=<SqueezeBackward4>)


tensor([0.1677, 0.2592, 0.2848, 0.2883], grad_fn=<SoftmaxBackward0>)

In [ ]:
tagger(torch.Tensor([1,0.1,1]))

tensor([-0.6074, -0.0218,  0.1246,  0.0366], grad_fn=<SqueezeBackward4>)


tensor([0.1475, 0.2649, 0.3067, 0.2809], grad_fn=<SoftmaxBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_a = nn.Linear(3,4)
        self.dense_b = nn.Linear(4,4)

    def forward(self, x):
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        print(x)
        return nn.functional.softmax(x,0)

tagger = POS_Tagger().to(device)
tagger(torch.Tensor(word))

tensor([ 0.3694, -0.3694,  0.1306,  0.5347], grad_fn=<TanhBackward0>)


tensor([0.2903, 0.1387, 0.2286, 0.3424], grad_fn=<SoftmaxBackward0>)

In [ ]:
tagger(torch.Tensor([900,111,55]))

tensor([0.2525, 0.0080, 0.4094, 0.8636], grad_fn=<TanhBackward0>)


tensor([0.2085, 0.1633, 0.2440, 0.3842], grad_fn=<SoftmaxBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.dense_a = nn.Linear(3,4)
        self.dense_b = nn.Linear(4,4)

    def forward(self, x):
        x = self.dense_a(x)
        x = nn.functional.relu(x)
        x = self.dense_b(x)
        x = nn.functional.relu(x)
        print(x)
        return nn.functional.softmax(x,0)

tagger = POS_Tagger().to(device)
tagger(torch.Tensor(word))

tensor([0.0000, 0.0000, 0.0000, 0.7568], grad_fn=<ReluBackward0>)


tensor([0.1949, 0.1949, 0.1949, 0.4154], grad_fn=<SoftmaxBackward0>)

In [ ]:
len(tokens)

7255

In [ ]:
import math
math.log(len(tokens),2)

12.824759898954108

In [ ]:
[1,0,0,0,0,0,0,0,0,0,0,0,0]

[1,1,0,0,0,0,0,0,0,0,0,0,0]

[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
enumerated_tokens

[(0, '0'),
 (1, '000'),
 (2, '000continue'),
 (3, '003'),
 (4, '004'),
 (5, '005'),
 (6, '006'),
 (7, '009'),
 (8, '05'),
 (9, '0x00'),
 (10, '0x1i'),
 (11, '1'),
 (12, '10'),
 (13, '100'),
 (14, '1000'),
 (15, '10000'),
 (16, '101'),
 (17, '102'),
 (18, '103'),
 (19, '104'),
 (20, '105'),
 (21, '107'),
 (22, '11'),
 (23, '1100'),
 (24, '12'),
 (25, '1200'),
 (26, '1250'),
 (27, '13'),
 (28, '1300'),
 (29, '1400'),
 (30, '1450'),
 (31, '15'),
 (32, '1500'),
 (33, '1600'),
 (34, '1700'),
 (35, '1800'),
 (36, '1850'),
 (37, '1900'),
 (38, '1950'),
 (39, '1st'),
 (40, '2'),
 (41, '20'),
 (42, '200'),
 (43, '2000'),
 (44, '2050'),
 (45, '2100'),
 (46, '2200'),
 (47, '2300'),
 (48, '2400'),
 (49, '2500'),
 (50, '26'),
 (51, '2600'),
 (52, '27'),
 (53, '2700'),
 (54, '2800'),
 (55, '29'),
 (56, '2nd'),
 (57, '3'),
 (58, '30'),
 (59, '300'),
 (60, '3000'),
 (61, '31'),
 (62, '32'),
 (63, '3300'),
 (64, '3500'),
 (65, '37'),
 (66, '39'),
 (67, '3rd'),
 (68, '4'),
 (69, '400'),
 (70, '4000'),
 

In [ ]:
translate = { tok:i for i,tok in enumerated_tokens }
translate

{'0': 0,
 '000': 1,
 '000continue': 2,
 '003': 3,
 '004': 4,
 '005': 5,
 '006': 6,
 '009': 7,
 '05': 8,
 '0x00': 9,
 '0x1i': 10,
 '1': 11,
 '10': 12,
 '100': 13,
 '1000': 14,
 '10000': 15,
 '101': 16,
 '102': 17,
 '103': 18,
 '104': 19,
 '105': 20,
 '107': 21,
 '11': 22,
 '1100': 23,
 '12': 24,
 '1200': 25,
 '1250': 26,
 '13': 27,
 '1300': 28,
 '1400': 29,
 '1450': 30,
 '15': 31,
 '1500': 32,
 '1600': 33,
 '1700': 34,
 '1800': 35,
 '1850': 36,
 '1900': 37,
 '1950': 38,
 '1st': 39,
 '2': 40,
 '20': 41,
 '200': 42,
 '2000': 43,
 '2050': 44,
 '2100': 45,
 '2200': 46,
 '2300': 47,
 '2400': 48,
 '2500': 49,
 '26': 50,
 '2600': 51,
 '27': 52,
 '2700': 53,
 '2800': 54,
 '29': 55,
 '2nd': 56,
 '3': 57,
 '30': 58,
 '300': 59,
 '3000': 60,
 '31': 61,
 '32': 62,
 '3300': 63,
 '3500': 64,
 '37': 65,
 '39': 66,
 '3rd': 67,
 '4': 68,
 '400': 69,
 '4000': 70,
 '43': 71,
 '4500': 72,
 '46': 73,
 '4624': 74,
 '49': 75,
 '4th': 76,
 '5': 77,
 '500': 78,
 '5000': 79,
 '52': 80,
 '55': 81,
 '5th': 82,
 '6

In [ ]:
tag_translate = { tok:i for i,tok in enumerated_tags }
tag_translate

{'.': 0,
 'ADJ': 1,
 'ADP': 2,
 'ADV': 3,
 'CONJ': 4,
 'DET': 5,
 'NOUN': 6,
 'NUM': 7,
 'PRON': 8,
 'PRT': 9,
 'VERB': 10,
 'X': 11}

In [ ]:
torch.rand(7255,9).shape

torch.Size([7255, 9])

In [ ]:
torch.rand(7255,9)[0]

tensor([0.7242, 0.0209, 0.5211, 0.5232, 0.7151, 0.3649, 0.3556, 0.9781, 0.0463])

In [ ]:
embedding = nn.Embedding(7255,9)
embedding[0]

TypeError: 'Embedding' object is not subscriptable

In [ ]:
embedding.weight

Parameter containing:
tensor([[ 1.6307,  0.1390, -0.7794,  ...,  1.3470,  0.1925, -0.4736],
        [ 0.8799,  2.4935,  0.5647,  ..., -0.4959,  0.0928, -0.3696],
        [ 0.9925,  1.4666, -1.3552,  ..., -0.4635,  0.5746, -0.7518],
        ...,
        [ 0.7539,  0.7821,  0.4856,  ..., -0.5455,  0.1813,  0.4380],
        [-0.2366,  1.0212, -0.4820,  ...,  0.3226, -1.3643, -0.2939],
        [-1.1159,  2.1360,  0.3178,  ...,  0.6585,  0.2188,  1.0489]],
       requires_grad=True)

In [ ]:
embedding.weight[0]

tensor([ 1.6307,  0.1390, -0.7794, -0.1370, -2.3883, -0.2021,  1.3470,  0.1925,
        -0.4736], grad_fn=<SelectBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(7255,9)
        self.dense_a = nn.Linear(9*7,9*7)
        self.dense_b = nn.Linear(9*7,17)

    def forward(self, x):
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        print(x)
        return nn.functional.softmax(x,0)

In [ ]:
tagger = POS_Tagger().to(device)
tagger(torch.Tensor([17,45,1000, 58 ,600,445,6969]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x7 and 3x4)

In [ ]:
embedding(torch.Tensor([17,45,1000, 58 ,600,445,6969]))

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [ ]:
embedding(torch.LongTensor([17,45,1000, 58 ,600,445,6969]))

tensor([[ 1.8155,  0.3148, -0.2364, -0.7067, -0.2668,  0.5239,  0.7680,  0.6081,
         -1.7904],
        [-0.3943, -0.1040,  0.3080, -0.6907, -0.4710, -1.2338,  1.3906,  1.4138,
         -0.6019],
        [-0.4590, -0.6338, -0.3684,  1.0082,  1.1837, -1.1174, -0.0201, -0.4318,
         -1.4246],
        [ 0.0755, -0.5938, -0.8859,  0.9162, -0.2318,  1.4807, -1.0724, -0.2050,
         -0.4065],
        [ 0.0157, -2.3883, -0.0792,  0.8809,  0.0059,  1.8296, -0.1575, -1.7466,
         -0.9411],
        [ 1.6622, -0.6083, -0.5618, -0.2969,  0.8193, -0.5773,  1.1873,  0.7723,
          1.6453],
        [-0.1605, -0.5825, -0.1114, -0.4367,  0.3061,  0.2951, -0.3493,  1.2924,
         -0.0941]], grad_fn=<EmbeddingBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(7255,9)
        self.dense_a = nn.Linear(9*7,9*7)
        self.dense_b = nn.Linear(9*7,17)

    def forward(self, x):
        x = self.embed(x)
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        return nn.functional.softmax(x,0)

In [ ]:
tagger = POS_Tagger().to(device)
tagger(torch.LongTensor([[17,45,1000, 58 ,600,445,6969]]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (7x9 and 63x63)

In [ ]:
torch.flatten(torch.LongTensor([[17,45,1000, 58 ,600,445,6969]]))

tensor([  17,   45, 1000,   58,  600,  445, 6969])

In [ ]:
torch.flatten(torch.LongTensor([[17,45,1000, 58 ,600,445,6969]]),1)

tensor([[  17,   45, 1000,   58,  600,  445, 6969]])

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(7255,9)
        self.dense_a = nn.Linear(9*7,9*7)
        self.dense_b = nn.Linear(9*7,17)

    def forward(self, x):
        x = self.embed(x)
        x = x.reshape(-1,9*7)
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        return nn.functional.softmax(x)

In [ ]:
tagger = POS_Tagger().to(device)

In [ ]:
tagger(torch.LongTensor([
    [17,45,1000, 58 ,600,445,6969],
    [17,45,1000, 58 ,600,445,6969],
    [19,45,1000, 58 ,600,445,6969]]))

<ipython-input-80-d988db8b6294>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


tensor([[0.0415, 0.0654, 0.0561, 0.0569, 0.0481, 0.0410, 0.0684, 0.0521, 0.0698,
         0.0526, 0.0732, 0.0643, 0.0354, 0.0636, 0.0974, 0.0478, 0.0662],
        [0.0415, 0.0654, 0.0561, 0.0569, 0.0481, 0.0410, 0.0684, 0.0521, 0.0698,
         0.0526, 0.0732, 0.0643, 0.0354, 0.0636, 0.0974, 0.0478, 0.0662],
        [0.0441, 0.0652, 0.0587, 0.0530, 0.0468, 0.0466, 0.0627, 0.0521, 0.0715,
         0.0541, 0.0690, 0.0631, 0.0363, 0.0654, 0.0915, 0.0516, 0.0683]],
       grad_fn=<SoftmaxBackward0>)

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(7255+2,9)
        self.dense_a = nn.Linear(9*7,9*7)
        self.dense_b = nn.Linear(9*7,len(tags))

    def forward(self, x):
        x = self.embed(x)
        x = x.reshape(-1,9*7)
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        return nn.functional.softmax(x)

In [ ]:
train,test = torch.utils.data.random_split(range(len(ds)), [0.8,0.2])

In [ ]:
train = list(train)
test = list(test)
train[:10]

[15001, 28885, 12310, 23095, 14685, 14179, 28025, 11863, 29086, 9359]

In [ ]:
tagger = POS_Tagger().to(device)

optimizer = torch.optim.Adam(tagger.parameters(), lr=0.001)

In [ ]:
import random

for x in range(5):
    total_loss = 0

    for x in range(10,len(train),10):

        indexes = train[x-10:x]

        x = []
        y = []

        for index in indexes:
            row = ds.iloc[index]
            text = ["<FILL>","<FILL>","<FILL>"] + row.tokenized_text + ["<FILL>","<FILL>","<FILL>"]
            tags = [None,None,None] + row.tags + [None,None,None]

            for _ in range(3):
                idx = random.randrange(3,len(text)-3)

                _tokens = text[idx-3:idx+4]
                _token_tag = tags[idx]

                text_codes = [ translate[token] for token in _tokens ]
                tag_code = tag_translate[_token_tag]

                x.append(text_codes)
                y.append(tag_code)

        x = torch.LongTensor(x)
        y = torch.LongTensor(y)

        optimizer.zero_grad()
        predict = tagger(x)

        loss = torch.nn.functional.cross_entropy(predict,y)
        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print("epoch loss:",total_loss)

<ipython-input-84-d597443ce60f>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


epoch loss: 5246.408755064011
epoch loss: 5240.356895446777
epoch loss: 5238.3201513290405
epoch loss: 5233.999708414078
epoch loss: 5232.17187833786


In [ ]:
from sklearn.metrics import f1_score

total_score = 0
steps = 0
with torch.no_grad():
    indexes = test

    x = []
    y = []

    for index in indexes:
        row = ds.iloc[index]
        text = ["<FILL>","<FILL>","<FILL>"] + row.tokenized_text + ["<FILL>","<FILL>","<FILL>"]
        tags = [None,None,None] + row.tags + [None,None,None]

        for _ in range(100):
            idx = random.randrange(3,len(text)-3)

            _tokens = text[idx-3:idx+4]
            _token_tag = tags[idx]

            text_codes = [ translate[token] for token in _tokens ]
            tag_code = tag_translate[_token_tag]

            x.append(text_codes)
            y.append(tag_code)

    x = torch.LongTensor(x)
    y = torch.LongTensor(y)

    predict = tagger(x).argmax(dim=1)

    print(predict)
    print(y)
    print(list(tag_translate.keys()))

    score = f1_score(y, predict,average='weighted')

    print(score)

<ipython-input-84-d597443ce60f>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


tensor([ 6,  5,  6,  ...,  7,  2, 10])
tensor([ 6,  5,  6,  ...,  7,  5, 10])
['.', 'ADJ', 'ADP', 'ADV', 'CONJ', 'DET', 'NOUN', 'NUM', 'PRON', 'PRT', 'VERB', 'X']
0.8496089152486763


In [ ]:
[ translate[x] for x in "you can make a second attack with this card on attack position".split()]

[7181, 1047, 3879, 115, 5586, 557, 7089, 6444, 1081, 4487, 557, 4851]

In [ ]:
tokenized = [ translate[x] for x in ["<FILL>","<FILL>","<FILL>"] + "you can make a second attack with this card on attack position".split() + ["<FILL>","<FILL>","<FILL>"] ]
tokenized

[7255,
 7255,
 7255,
 7181,
 1047,
 3879,
 115,
 5586,
 557,
 7089,
 6444,
 1081,
 4487,
 557,
 4851,
 7255,
 7255,
 7255]

In [ ]:
nltk.tag.pos_tag("you can make a second attack with this card on attack position".split(),tagset="universal")

[('you', 'PRON'),
 ('can', 'VERB'),
 ('make', 'VERB'),
 ('a', 'DET'),
 ('second', 'ADJ'),
 ('attack', 'NOUN'),
 ('with', 'ADP'),
 ('this', 'DET'),
 ('card', 'NOUN'),
 ('on', 'ADP'),
 ('attack', 'NOUN'),
 ('position', 'NOUN')]

In [ ]:
slices = [ tokenized[x-3:x+4] for x in range(3,len(tokenized)-3) ]
slices

[[7255, 7255, 7255, 7181, 1047, 3879, 115],
 [7255, 7255, 7181, 1047, 3879, 115, 5586],
 [7255, 7181, 1047, 3879, 115, 5586, 557],
 [7181, 1047, 3879, 115, 5586, 557, 7089],
 [1047, 3879, 115, 5586, 557, 7089, 6444],
 [3879, 115, 5586, 557, 7089, 6444, 1081],
 [115, 5586, 557, 7089, 6444, 1081, 4487],
 [5586, 557, 7089, 6444, 1081, 4487, 557],
 [557, 7089, 6444, 1081, 4487, 557, 4851],
 [7089, 6444, 1081, 4487, 557, 4851, 7255],
 [6444, 1081, 4487, 557, 4851, 7255, 7255],
 [1081, 4487, 557, 4851, 7255, 7255, 7255]]

In [ ]:
tagger(torch.LongTensor(slices)).argmax(dim=1)

<ipython-input-84-d597443ce60f>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


tensor([ 8, 10, 10,  5,  1,  6,  2,  5,  6,  2,  6,  6])

In [ ]:
for cls in tagger(torch.LongTensor(slices)).argmax(dim=1):
    print(enumerated_tags[cls])

(8, 'PRON')
(10, 'VERB')
(10, 'VERB')
(5, 'DET')
(1, 'ADJ')
(6, 'NOUN')
(2, 'ADP')
(5, 'DET')
(6, 'NOUN')
(2, 'ADP')
(6, 'NOUN')
(6, 'NOUN')


<ipython-input-84-d597443ce60f>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


In [ ]:
def pos_tag(string):
    tokenized = [ translate[x] for x in ["<FILL>","<FILL>","<FILL>"] + string.lower().split() + ["<FILL>","<FILL>","<FILL>"] ]
    slices = [ tokenized[x-3:x+4] for x in range(3,len(tokenized)-3) ]
    prediction = tagger(torch.LongTensor(slices)).argmax(dim=1)
    tokens = string.split()
    for i,cls in enumerate(prediction):
        print(tokens[i],enumerated_tags[cls][1])

In [ ]:
pos_tag("You can make a second attack with this card on attack position")

You PRON
can VERB
make VERB
a DET
second ADJ
attack NOUN
with ADP
this DET
card NOUN
on ADP
attack NOUN
position NOUN


<ipython-input-84-d597443ce60f>:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return nn.functional.softmax(x)


In [ ]:
nltk.tag.pos_tag("You can make a second attack with this card on attack position".split(),tagset="universal")

[('You', 'PRON'),
 ('can', 'VERB'),
 ('make', 'VERB'),
 ('a', 'DET'),
 ('second', 'ADJ'),
 ('attack', 'NOUN'),
 ('with', 'ADP'),
 ('this', 'DET'),
 ('card', 'NOUN'),
 ('on', 'ADP'),
 ('attack', 'NOUN'),
 ('position', 'NOUN')]

In [ ]:
pos_tag("With no heirs the will of the late king decrees that the next monarch will be elected by the people and thus begins your fight for the throne")

KeyError: 'heirs'

In [ ]:
tags = ds.tags.map(lambda x: set(x))
tags = functools.reduce(lambda x,y : x.union(y),tags)
tags

{'.',
 'ADJ',
 'ADP',
 'ADV',
 'CONJ',
 'DET',
 'NOUN',
 'NUM',
 'PRON',
 'PRT',
 'VERB',
 'X'}

In [ ]:
from torch import nn

class POS_Tagger(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(7255+2,9)
        self.dense_a = nn.Linear(9*7,9*7)
        self.dense_b = nn.Linear(9*7,len(tags))

    def forward(self, x):
        x = self.embed(x)
        x = x.reshape(-1,9*7)
        x = self.dense_a(x)
        x = nn.functional.tanh(x)
        x = self.dense_b(x)
        x = nn.functional.tanh(x)
        return nn.functional.softmax(x)

In [ ]:
tagger = POS_Tagger().to(device)

def pos_tag(string):
    tokenized = [ translate[x] for x in ["<FILL>","<FILL>","<FILL>"] + string.lower().split() + ["<FILL>","<FILL>","<FILL>"] ]
    slices = [ tokenized[x-3:x+4] for x in range(3,len(tokenized)-3) ]
    prediction = tagger(torch.LongTensor(slices)).argmax(dim=1)
    tokens = string.split()
    for i,cls in enumerate(prediction):
        print(tokens[i],enumerated_tags[cls][1])

In [ ]:
pos_tag("You can make a second attack with this card on attack position")